### ISSUE TITLE
Sample config for TI I2C Driver/SimpleLink SDK

### ISSUE THREAD

**Issue by piLinux** [Sensirion/embedded-common#92]
Hi, can you provide any demo for the TI I2C driver or a guideline to integrate with TI SimpleLink SDK?
Thanks!

**Comment by MBjoern** [comment]
Hi piLinux

Unfortunately, we don't have a demo for die TI I2C driver or related guidance for integration with TI SimpleLink SDK.

Our available sample implementations can be found [here](https://github.com/Sensirion/embedded-common/tree/master/i2c/sample-implementations)

If you end up with a working sample implementation for the TI I2C Driver, feel free to open a corresponding PR.

Best regards
